title: My Portfolio of Showcase Projects in Statistics and Data Science
subtitle: Max Johansson
author: 
  name: Max Johansson
  email: max.f.johansson@outlook.com
show_downloads: FALSE
theme: jekyll-theme-Slate
